{% set name = "xilinx-runtime" %}
{% set version = "2.13.466" %}
{% set quarter = "202210" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Xilinx/XRT/archive/refs/tags/{{ quarter }}.{{ version }}.tar.gz
  sha256: d73d8366f6f6d66bfdcb67e72135f559a4d95644c5416c27dea79c235953fd20
  patches:
    - patches/0001-disable-werror.patch
    - patches/0002-xspi-array-patch.patch
    - patches/0003-prid64-macro-usage.patch
    - patches/0004-icd.patch
    - patches/0005-no-static-linkage.patch
    - patches/0006-fix-python-rm-dkms-general-cmake.patch
    - patches/0007-fix-pkg-config.patch
    - patches/0008-no-version-for-dkms.patch
    - patches/0009-fix-cmake-install-prefix.patch
    - patches/0010-fix-ocl.patch
    - patches/0011-no-cloud-daemon.patch
    - patches/0012-fix-xbflash-install.patch
    - patches/0013-no-setup-script.patch
    - patches/0014-fix-appdebug-install.patch
    - patches/0015-remove-static-libs.patch
    - patches/0016-rely-on-pkg-config-metadata-for-finding-OpenCL.patch

build:
  number: 13
  skip: true  # [not linux]
  ignore_run_exports_from:
    - libdrm
    - libcurl
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pkg-config
    - git

  host:
    - python
    - pybind11
    - libboost-devel
    - protobuf
    - libprotobuf
    - rapidjson
    - libuuid
    - libdrm
    - clhpp
    - libcurl
    - openssl
    - ncurses

  run:
    - python

test:
  imports:
    - pyxrt
  commands:
    - xbutil --help
    - xclbinutil --help

about:
  home: https://www.origin.xilinx.com/products/design-tools/vitis/xrt.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Xilinx Runtime for Heterogenous Acceleration
  description: Xilinx Runtime for Heterogenous Acceleration
  dev_url: https://github.com/Xilinx/XRT
  doc_url: https://xilinx.github.io/XRT

extra:
  recipe-maintainers:
    - stsoe
    - aaronn-xilinx
    - bryanloz-xilinx
    - timsnyder
